### ISSUE TITLE
Event start time doesnt match the shift start time

### ISSUE THREAD

**Issue by DeeruBhai** [SmartMach/webapp-v1#61]
When
I hover above the downtime graph

then
the event start time and shift start time should be equal

Actual
the event start time and shift start time should be equal 
![Screenshot (412)](https://user-images.githubusercontent.com/118270248/205823956-6b67e9ad-72d1-4c5a-8f42-f02ca379f12b.png)
![image](https://user-images.githubusercontent.com/118270248/205824756-d74bb6fd-da99-4195-8f50-4fef2a38d1e8.png)

**Comment by ManikandanS8377** [comment]
![image](https://user-images.githubusercontent.com/80878236/206095355-eca7f67c-bb3b-455e-a84d-5fff65b35627.png)
This Error is identified. Actually, the data of the particular Time for that machine has been created in the Database. But the Shift date is different. This case is not happening as a periodic issue. We will check and find the exact root cause of the incident

**Comment by DeeruBhai** [comment]
![image](https://user-images.githubusercontent.com/118270248/207594443-4b757e08-30f7-408f-94e5-391a1e654a45.png)
