### ISSUE TITLE
site user access control save button not working

### ISSUE THREAD

**Issue by tamizh061** [SmartMach/webapp-v1#79]
when
give some acces for sit user
then
click on the save button must be save the accesses
actual
given access is not  saved 
[screen-recorder-thu-dec-08-2022-16-18-15.webm](https://user-images.githubusercontent.com/118597994/206429056-13a22377-f588-4381-9329-43e87e1eeb0e.webm)

**Comment by strategynaveen** [comment]
root cause : actually this kind of issue is technical issue for my site before im thinking on each and every time the user firs select role and after click access control its gets controller based new records arrangement so. if any change save its working but if change the access then one more click the access control before changes is refreshed.

solution : this time the function logic get the cancel and back button its apply because every changes after save its not save click cancel button its refreshed the access control  page
